### ISSUE TITLE
Workload type choice support

### ISSUE THREAD

**Issue by pigletfly** [crossplane/oam-kubernetes-runtime#22] opened 2020-05-18 11:41 UTC
why we are using Deployment? Can we use other kinds of kubernetes workload type? such as StatefulSet.

**Comment by ryanzhang-oss** [comment] 2020-05-18 18:10
IIRC, this is a similar request to https://github.com/crossplane/oam-kubernetes-runtime/issues/13. I wonder if our responses, especially https://github.com/crossplane/oam-kubernetes-runtime/issues/13#issuecomment-622176013, answer your question?

**Comment by ryanzhang-oss** [comment] 2020-05-18 18:10
You are more than welcome to propose a StatefulSet workload type.

**Comment by ryanzhang-oss** [comment] 2020-05-29 21:15
close this as it's a duplicate of  #13

**Closed by ryanzhang-oss** 2020-05-29 21:15 UTC
