### ISSUE TITLE
remove all child resources when the OAM controllers exit

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/oam-kubernetes-runtime#67] opened 2020-07-02 02:10 UTC
Currently, all OAM applications are intact even after the appConfig controller exists.

**Comment by wonderflow** [comment] 2020-07-02 02:16
This is not a bug. In fact it's a MUST in K8s. Controller process can crash/exit, but K8s object won't affect.

**Comment by ryanzhang-oss** [comment] 2020-07-06 22:39
Let me clarify.  The child resources generated by the controllers (component/traits/deployment/service) are still there after the OAM controllers exit.  I wonder if the controllers don't clean up after themselves they who should?

**Comment by wonderflow** [comment] 2020-10-27 02:41
K8s uses [ownerReference mechanism](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/) do GC for this case, as we have set ownerReference for all child resources（component/traits/deployment/service..） created by appconfig, so even the controller exit, if we delete appconfig cr, these child resource will also be deleted(garbage collection).

Closing as it was not an issue.

**Closed by wonderflow** 2020-10-27 02:41 UTC
Labels: bug, enhancement
