### ISSUE TITLE
When a Component Workload is deleted by mistake, the OAM Runtime is expected to automatically recreate the workload

### ISSUE THREAD

**Issue by CoderPoet** [crossplane/oam-kubernetes-runtime#84] opened 2020-07-06 09:43 UTC
Currently, because the OAM Runtime only watches the component and Appconfig, it does not go to the Watch Workload CRD.

So workload changes are not notified to the OAM Runtime

This scenario might consider designing an elegant solution to the problem

**Comment by wonderflow** [comment] 2020-07-06 11:09
I think periodically check can be a quick fix for this issue.

**Comment by CoderPoet** [comment] 2020-07-06 14:46
> I think periodically check can be a quick fix for this issue.

Is it better to use another coroutine to do this global periodic check, or is it better to have the check logic built into the DAG dependency manager?

**Comment by ryanzhang-oss** [comment] 2020-07-06 21:43
I think it's ok as long as the controller's reconcile logic is executed periodically. The issue is we need to make sure that the "re-sync" is triggered

**Comment by CoderPoet** [comment] 2020-07-07 06:49
I am very sorry that this issue may not be a problem. @wonderflow  @ryanzhang-oss 

After reading the source code,I found that OAM Runtime uses the Controller-Runtime RequeueAfter mechanism

Setting the default one minute rerequeue request will trigger appConfig reconcile every minute

[RequeueAfter 1min](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/pkg/controller/v1alpha2/applicationconfiguration/applicationconfiguration.go#L236)

[Controller Runtime RequeueAfter](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L245)

**Comment by wonderflow** [comment] 2020-07-07 09:30
Will it re-create workload which is deleted by mistake? @CoderPoet

**Comment by CoderPoet** [comment] 2020-07-07 10:43
> Will it re-create workload which is deleted by mistake? @CoderPoet

Yes, today when I test, I found it will automatically re-trigger the Reconcile logic every minute, then auto re-create the workload.

So I read the code carefully and found out that It should be due to the use of ReuqueAfter mechanism

**Comment by wonderflow** [comment] 2020-07-07 10:46
Thanks, then I'll close this issue.

**Closed by wonderflow** 2020-07-07 10:46 UTC
Labels: enhancement
